name: Proposer une amélioration
description: Une idée pour l'application Elymon pour Android.
title: "[Idée] <résumé en quelques mots>"
labels: [enhancement]
body:
- type: textarea
  id: problem
  attributes:
    label: Le besoin
    description: Qu'est-ce qui te gêne ou te manque aujourd'hui ?
    placeholder: "Exemple : je n'arrive pas à ouvrir le PC Pokémon avec les contrôles tactiles."
  validations:
    required: true

- type: textarea
  id: idea
  attributes:
    label: Ta proposition
    description: Ce que tu voudrais voir ajouté, changé ou retiré.
  validations:
    required: true

- type: textarea
  id: more
  attributes:
    label: Autre chose ?
  validations:
    required: false
