package com.elythera.elymon.controls;

import android.app.Activity;
import android.app.ActivityManager;
import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

import androidx.appcompat.app.AlertDialog;

import com.elythera.elymon.ElymonConfig;

import net.kdt.pojavlaunch.R;
import net.kdt.pojavlaunch.Tools;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Elymon's touch controls: the default layout (assets/default.json) and the Android key
 * bindings it relies on.
 *
 * <p>Two hooks call it: AsyncAssetManager.unpackSingleFiles at every app start
 * ({@link #onAppStart}), on a background thread of the launcher process, and
 * ControlLayout.loadLayout when a layout is shown ({@link #showPendingNotice}), in the game
 * process or the editor.
 *
 * <p>The layout is generated by tools/elymon/controls/make_layout.py and checked by
 * tools/elymon/check-controls.py, which also checks that the last entry of {@link #LAYOUTS} is
 * the SHA-256 of the shipped default.json.
 */
public final class ElymonControls {
    private static final String TAG = "ElymonControls";

    /**
     * Every default.json an Elymon build installed, oldest first: {version, SHA-256}. A
     * controlmap/default.json with one of these hashes was never edited by the player and is
     * replaced by the shipped layout. The last entry is the shipped layout; its version names
     * the copy written beside a layout the player edited (elymon-&lt;version&gt;.json).
     * Add an entry (never edit one) whenever assets/default.json changes.
     */
    static final String[][] LAYOUTS = {
            // upstream Amethyst's default.json, installed by the first builds (1.0.0-alpha.1)
            {"amethyst", "d92a182bde65a19c1c9edb1291f8dde2ff9efcbb95b9a7745c3e591b85f7516a"},
            {"1", "97b78cae6b5221a225c2eb71c1b35af86e02d55daec1c521a798ec0f141667bc"},
    };

    static final String LAYOUT_ASSET = "default.json";
    static final String POLICY_ASSET = "elymon/android-policy.json";
    static final String KEY_HISTORY_ASSET = "elymon/controls-keybindings.json";

    // Launcher-process state. The game process never writes these preferences (each process
    // caches its own copy): what it must change lives in NOTICE_FILE.
    private static final String PREFS = "elymon_controls";
    private static final String PREF_LAYOUT_SHA = "layout_sha256";
    private static final String PREF_LAYOUT_OFFERED = "layout_offered_version";
    private static final String PREF_KEYBINDINGS = "keybindings_applied";
    /** Holds the name of a layout saved beside the player's, until the player has been told. */
    private static final String NOTICE_FILE = "elymon-controls-notice.txt";

    private ElymonControls() {}

    /** Launcher start, background thread: layout first, then key bindings. Never throws. */
    public static void onAppStart(Context context) {
        Context app = context.getApplicationContext();
        SharedPreferences prefs = app.getSharedPreferences(PREFS, Context.MODE_PRIVATE);
        try {
            installLayout(app, prefs);
        } catch (Throwable t) {
            Log.w(TAG, "Default layout not updated", t);
        }
        try {
            migrateKeybindings(app, prefs);
        } catch (Throwable t) {
            Log.w(TAG, "Key bindings not migrated", t);
        }
    }

    // ------------------------------------------------------------------ layout

    private static void installLayout(Context app, SharedPreferences prefs) throws IOException {
        byte[] asset = readAsset(app, LAYOUT_ASSET);
        String sha = LayoutInstaller.sha256(asset);
        String version = versionOf(sha);
        List<String> known = new ArrayList<String>();
        for (String[] layout : LAYOUTS) {
            known.add(layout[1]);
        }
        boolean offered = version.equals(prefs.getString(PREF_LAYOUT_OFFERED, null));
        LayoutInstaller.Result result = LayoutInstaller.apply(new File(Tools.CTRLMAP_PATH), asset, version,
                prefs.getString(PREF_LAYOUT_SHA, null), known, offered);
        SharedPreferences.Editor editor = prefs.edit();
        if (result.installedSha != null) {
            editor.putString(PREF_LAYOUT_SHA, result.installedSha);
        }
        if (result.action == LayoutInstaller.Action.KEPT_PLAYER_LAYOUT && !offered) {
            // told once per shipped layout, the next time a layout is shown
            LayoutInstaller.writeAtomic(noticeFile(app), result.alongside.getBytes(StandardCharsets.UTF_8));
            editor.putString(PREF_LAYOUT_OFFERED, version);
        }
        editor.apply();
        Log.i(TAG, "Default layout " + version + ": " + result.action
                + (result.alongside != null ? " (" + result.alongside + ")" : ""));
    }

    /** The version of a shipped layout, from its hash; a short hash if it is not listed. */
    static String versionOf(String sha) {
        for (String[] layout : LAYOUTS) {
            if (layout[1].equals(sha)) {
                return layout[0];
            }
        }
        return sha.substring(0, 8);
    }

    /**
     * When a new Elymon layout was saved beside a layout the player edited, says so once, in
     * French, over the screen that shows the controls. UI thread; activity context.
     */
    public static void showPendingNotice(Context context) {
        if (!(context instanceof Activity)) {
            return;
        }
        final Activity activity = (Activity) context;
        final File notice = noticeFile(activity);
        if (!notice.isFile()) {
            return;
        }
        String fileName;
        try {
            fileName = new String(readFully(new FileInputStream(notice)), StandardCharsets.UTF_8).trim();
        } catch (IOException e) {
            fileName = "";
        }
        // told at most once, even if the dialog cannot show
        notice.delete();
        if (!fileName.matches("[A-Za-z0-9._-]+\\.json")) {
            return;
        }
        String message = activity.getString(R.string.elymon_controls_new_layout_message, fileName,
                activity.getString(R.string.mcl_option_customcontrol),
                activity.getString(R.string.global_load),
                activity.getString(R.string.customctrl_selectdefault));
        try {
            new AlertDialog.Builder(activity)
                    .setTitle(R.string.elymon_controls_new_layout_title)
                    .setMessage(message)
                    .setPositiveButton(R.string.elymon_controls_ok, null)
                    .show();
        } catch (RuntimeException e) {
            Log.w(TAG, "New layout notice not shown", e);
        }
    }

    private static File noticeFile(Context context) {
        return new File(context.getFilesDir(), NOTICE_FILE);
    }

    // ------------------------------------------------------------------ key bindings

    private static void migrateKeybindings(Context app, SharedPreferences prefs) throws IOException {
        KeybindingMigration migration = KeybindingMigration.parse(
                new String(readAsset(app, POLICY_ASSET), StandardCharsets.UTF_8),
                new String(readAsset(app, KEY_HISTORY_ASSET), StandardCharsets.UTF_8));
        if (migration.id.equals(prefs.getString(PREF_KEYBINDINGS, null))) {
            return;
        }
        if (isGameProcessAlive(app)) {
            // the game would write its own options.txt back on exit: next start
            Log.i(TAG, "Key bindings: the game is running, migration postponed");
            return;
        }
        File options = new File(new File(Tools.DIR_GAME_HOME, ElymonConfig.INSTANCE_REL), "options.txt");
        if (options.isFile()) {
            String text = new String(readFully(new FileInputStream(options)), StandardCharsets.UTF_8);
            KeybindingMigration.Result result = migration.reconcile(text);
            if (!result.changed.isEmpty()) {
                LayoutInstaller.writeAtomic(options, result.text.getBytes(StandardCharsets.UTF_8));
                Log.i(TAG, "Key bindings moved to the Android keys: " + result.changed);
            }
        }
        // Without options.txt (or without key_ lines), DefaultOptions applies keybindings.txt
        // itself at the first start of the game.
        prefs.edit().putString(PREF_KEYBINDINGS, migration.id).apply();
    }

    /** Same test as ElymonLaunch: this app's :game process (MainActivity) is running. */
    private static boolean isGameProcessAlive(Context context) {
        ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        if (manager == null) return false;
        List<ActivityManager.RunningAppProcessInfo> processes = manager.getRunningAppProcesses();
        if (processes == null) return false;
        for (ActivityManager.RunningAppProcessInfo process : processes) {
            if (process.processName != null && process.processName.endsWith(":game")) {
                return true;
            }
        }
        return false;
    }

    // ------------------------------------------------------------------ io

    private static byte[] readAsset(Context context, String name) throws IOException {
        return readFully(context.getAssets().open(name));
    }

    private static byte[] readFully(InputStream in) throws IOException {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            byte[] buffer = new byte[16384];
            int n;
            while ((n = in.read(buffer)) > 0) {
                out.write(buffer, 0, n);
            }
            return out.toByteArray();
        } finally {
            in.close();
        }
    }
}
